version: "3"

services:

   postgres:
     image: postgres
     container_name: postgres
     restart: on-failure
     volumes:
       - D:\volume\postgres-keycloack:/var/lib/postgresql/data
     environment:
       POSTGRES_DB: keycloak
       POSTGRES_USER: keycloak
       POSTGRES_PASSWORD: password

   keycloak:
     image: quay.io/keycloak/keycloak:15.0.1
     container_name: keycloak
     restart: on-failure
     environment:
       DB_VENDOR: POSTGRES
       DB_ADDR: postgres
       DB_DATABASE: keycloak
       DB_USER: keycloak
       DB_SCHEMA: public
       DB_PASSWORD: password
       KEYCLOAK_USER: admin
       KEYCLOAK_PASSWORD: Pa55w0rd.
     ports:
       - 8080:8080